The RedMatrix: RedMatrix\RedDAV\RedPrincipalBackend Class Reference
RedMatrix\RedDAV\RedPrincipalBackend Class Reference
PrincipalBackend implementation of Sabre\DAVACL\PrincipalBackend\AbstractBackend.
Public Member Functions
getPrincipalsByPrefix ($prefixPath)
getPrincipalByPath ($path)
updatePrincipal ($path, DAV\PropPatch $propPatch)
searchPrincipals ($prefixPath, array $searchProperties, $test= 'allof')
getGroupMembership ($principal)
getGroupMemberSet ($principal)
setGroupMemberSet ($principal, array $members)
Detailed Description
PrincipalBackend implementation of Sabre\DAVACL\PrincipalBackend\AbstractBackend.
This backend provides principals for DAV from the RedMatrix channels and collections. I am not yet completely sure how this will map with all the other advanced concepts of RedMatrix.
We have custom principal URL schemas. All user principals are in a collection under 'principals/channels' and all group principals are in a collection under 'principals/collections'.
Todo:
right now we use xcan_hash as the uri. Maybe it would be nicer to use xchan_addr?
Author
Klaus Weidenbach
License:
http://opensource.org/licenses/mit-license.php The MIT License (MIT)
Member Function Documentation
RedMatrix\RedDAV\RedPrincipalBackend::getGroupMemberSet ($principal)
Returns the list of members for a group-principal
Parameters
string $principal
Exceptions
\Sabre\DAV\Exception\NotFound
Returns
array
RedMatrix\RedDAV\RedPrincipalBackend::getGroupMembership ($principal)
Returns the list of groups a principal is a member of
Parameters
string $principal
Exceptions
\Sabre\DAV\Exception\NotFound
Returns
array
RedMatrix\RedDAV\RedPrincipalBackend::getPrincipalByPath ($path)
Returns a specific principal, specified by it's path. The returned structure should be the exact same as from getPrincipalsByPrefix.
Todo:
this could get optimized for sure!
Parameters
string $path
Returns
array
Referenced by RedMatrix\RedDAV\RedPrincipalBackend\getGroupMemberSet(), and RedMatrix\RedDAV\RedPrincipalBackend\getGroupMembership().
RedMatrix\RedDAV\RedPrincipalBackend::getPrincipalsByPrefix ($prefixPath)
Returns a list of principals based on a prefix.
This prefix will often contain something like 'principals'. You are only expected to return principals that are in this base path.
You are expected to return at least a 'uri' for every user, you can return any additional properties if you wish so. Common properties are: {DAV:}displayname {http://sabredav.org/ns}email-address - This is a custom SabreDAV field that's actually injected in a number of other properties. If you have an email address, use this property.
Parameters
string $prefixPath principals/channels or principals/collections are available
Exceptions
\Sabre\DAV\Exception\NotFound if another path was requested
Returns
array
Referenced by RedMatrix\RedDAV\RedPrincipalBackend\getPrincipalByPath().
RedMatrix\RedDAV\RedPrincipalBackend::searchPrincipals ($prefixPath, array $searchProperties, $test = 'allof')
This method is used to search for principals matching a set of properties.
This search is specifically used by RFC3744's principal-property-search REPORT.
The actual search should be a unicode-non-case-sensitive search. The keys in searchProperties are the WebDAV property names, while the values are the property values to search on.
By default, if multiple properties are submitted to this method, the various properties should be combined with 'AND'. If $test is set to 'anyof', it should be combined using 'OR'.
This method should simply return an array with full principal uri's.
If somebody attempted to search on a property the backend does not support, you should simply return 0 results.
You can also just return 0 results if you choose to not support searching at all, but keep in mind that this may stop certain features from working.
Parameters
string $prefixPath
array $searchProperties
string $test
Returns
array
RedMatrix\RedDAV\RedPrincipalBackend::setGroupMemberSet ($principal, array $members)
Updates the list of group members for a group principal.
The principals should be passed as a list of uri's.
Parameters
string $principal
array $members
Returns
void
RedMatrix\RedDAV\RedPrincipalBackend::updatePrincipal ($path, DAV\PropPatch $propPatch)
Updates one ore more webdav properties on a principal.
The list of mutations is stored in a Sabre\DAV\PropPatch object. To do the actual updates, you must tell this object which properties you're going to process with the handle() method.
Calling the handle method is like telling the PropPatch object "I promise I can handle updating this property".
Read the PropPatch documenation for more info and examples.
Parameters
string $path
\Sabre\DAV\PropPatch $propPatch
Returns
void
The documentation for this class was generated from the following file:
include/RedDAV/RedPrincipalBackend.php